[".tmux/plugins/tpm"]
   type = "archive"
   url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
   exact = true
   stripComponents = 1
   refreshPeriod = "168h"

[".config/kitty/current-theme.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/master/extras/kitty/tokyonight_night.conf"
    refreshPeriod = "168h"

[".config/iterm2/tokyonight_night.itermcolors"]
    type = "file"
    url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/master/extras/iterm/tokyonight_night.itermcolors"
    refreshPeriod = "168h"

{{ $starshipVersion := "1.17.1" -}}
{{ $starshipTgz := "" -}}
{{ if eq .chezmoi.os "darwin" -}}
{{   $starshipTgz = "starship-aarch64-apple-darwin.tar.gz" -}}
{{ else -}}
{{  if eq .chezmoi.arch "arm64" -}}
{{   $starshipTgz = "starship-aarch64-unknown-linux-musl.tar.gz" -}}
{{  else -}}
{{   $starshipTgz = "starship-x86_64-unknown-linux-gnu.tar.gz" -}}
{{  end -}}
{{ end -}}
{{ if $starshipTgz -}}
[".local/bin/starship"]
    type = "archive-file"
    url = "https://github.com/starship/starship/releases/download/v{{ $starshipVersion }}/{{ $starshipTgz }}"
    path = "starship"
{{ end -}}
