[".tmux/plugins/tpm"]
   type = "git-repo"
   url = "https://github.com/tmux-plugins/tpm.git"
   refreshPeriod = "168h"

[".config/kitty/current-theme.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/master/extras/kitty/tokyonight_night.conf"
    refreshPeriod = "168h"

[".config/iterm2/tokyonight_night.itermcolors"]
    type = "file"
    url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/master/extras/iterm/tokyonight_night.itermcolors"
    refreshPeriod = "168h"
